### ISSUE TITLE
Maybe something other than tmux is available for Windows?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [rohanrhu/gdb-frontend#40]
GDB can be used on Windows with MinGW projects. There is no problem.
But **Tmux** is not used, compiled for Windows, or nobody has tried it.
Is there another alternative to tmux for Windows?
Maybe we can use it on Windows. This way GDB Frontend will also support Windows.

**Comment by rohanrhu** [comment]
The problem is not terminal multiplexing about Windows. I can make a terminal multiplexer for Windows but it is not the main problem.

Main problem is GDB's Windows version's main-thread is being blocked during application runtime. This situation maybe changed/solved in new versions of GDB, I've not checked it yet but I will check it out soon.

**Comment by rohanrhu** [comment]
By the way, I had talked with GDB devs, they just said me it is possible but hard to make and nobody wants to implement it yet.

**Comment by SeanTolstoyevski** [comment]
Thank you for your answer, @rohanrhu.

You can close this issue off if you wish.
