### ISSUE TITLE
gdb prompt is behind bottom status bar

### ISSUE THREAD

**Issue by grooverdan** [rohanrhu/gdb-frontend#42]
![image](https://user-images.githubusercontent.com/462287/149264963-dbd4ce39-d0ba-4009-a89d-0e5d872af7ac.png)

**Comment by rohanrhu** [comment]
Oh this problem 😔 I have yet to see this problem on my computer 🤭 but someone however has this problem. I will fix it soon.

I have some questions:
* What is your browser?
* What is your screen resolution and screen scale?

Thank youuuu soo much for feedback. 😊

**Comment by grooverdan** [comment]
firefox 95.0.2
1920 x 1080 @ 100%

**Comment by rohanrhu** [comment]
> firefox 95.0.2
> 1920 x 1080 @ 100%

I just checked it out with someone has this problem. It is happening on Firefox's Linux version. It is related to Xterm.js (looks like it has a bug) and Firefox on Linux.  Sooo I will look for a solution, you can use Chrome/Chromium instead until resolving this issue.

With Chrome you can run the debugger as a standalone app, so you will have more vertical space to work :)

```bash
chromium --app=http://127.0.0.1:5550/terminal/
```

I know some people don't want to use Chrome for some privacy reasons but since Chromium is also open source and good for privacy, you can use it if you consider this reason to use Firefox.

This opens the debugger as a standalone app. It looks like this:

![image](https://user-images.githubusercontent.com/1125150/151576691-13801088-48f7-4106-a944-52d6eba55bbe.png)
![image](https://user-images.githubusercontent.com/1125150/151576720-e03dad54-6cc7-482c-883b-c816dd80f094.png)

**Comment by grooverdan** [comment]
Thanks for looking into detail as to the cause of this and the alternative

**Comment by rohanrhu** [comment]
> Thanks for looking into detail as to the cause of this and the alternative

Thank you tooo.

**Comment by rohanrhu** [comment]
I'm closing this issue with the latest version xterm.js is up to date. If anyone has this issue again, please re-open.
